# Generated by Django 3.1.1 on 2020-10-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_chapter_image_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='chapter',
        ),
        migrations.AlterField(
            model_name='chapter',
            name='book',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
