# Generated by Django 3.1.2 on 2020-10-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20201014_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='text',
            field=models.TextField(default='No Chapter Text'),
        ),
    ]
